export default [
  {
    id: 1,
    name: `P2P Tic Tac Toe`,
    link: "https://p2p-tic-tac-toe.netlify.app/",
    image: "p2p_tic_tac_toe",
    techStack: [
      "ReactJs",
      "Socket.io",
      "NodeJs",
      "MongoDB",
      "HTML5",
      "CSS",
      "Javascript",
      "Heroku",
    ],
    desc: "It is a multiplayer Tic-Tac-Toe game that can played offline (vs computer) or online (vs another player)",
  },
  {
    id: 2,
    name: `Memories App`,
    link: "https://uk-memories-app.netlify.app/",
    image: "memories",
    techStack: [
      "ReactJs",
      "NodeJs",
      "MongoDB",
      "HTML5",
      "MaterialUI",
      "Javascript",
      "Heroku",
    ],
    desc: "A scalable Full Stack Web App which performs all CRUD operations stores data in a database via API call to the server",
  },
  {
    id: 3,
    name: `Basic Front-end based SQL Editor`,
    link: "https://react-sql-editor.netlify.app/",
    image: "sql_editor",
    techStack: ["ReactJs", "HTML5", "Javascript", "CSS"],
    desc: "A scalable Full Stack Web App which performs all CRUD operations stores data in a database via API call to the server",
  },
  {
    id: 4,
    name: "Anime Weeb",
    link: "https://utkarshkalra.github.io/anime-weeb/",
    image: "anime_weeb",
    techStack: [
      "NodeJs",
      "MongoDB",
      "HTML5",
      "Bootstrap",
      "Javascript",
      "Heroku",
    ],
    desc: "A Website to help new Anime viewers in finding good quality Animes and where to Watch them",
  },

  {
    id: 5,
    name: "Mongodb Documentation",
    link: "https://utkarshkalra.github.io/anime-weeb/",
    image: "anime_weeb",
    techStack: [
      "NodeJs",
      "MongoDB",
      "HTML5",
      "Bootstrap",
      "Javascript",
      "Heroku",
    ],
    desc: "A Website to help new Anime viewers in finding good quality Animes and where to Watch them",
  },
];
