export const experienceList = [
  {
    name: "PolicyBazaar.com",
    location: "Gurgaon",
    position: "Full Stack Developer",
    duration: "Jan 2023 - Mar 2025",
    description: [
      "Conducted performance audits and implemented optimizations, resulting in a 30% reduction in page load times.",
      "Integrated Truecaller SDK for seamless login on the website using WebSocket-based backend architecture and React context for state management.",
      "Streamlined a 5-10 pages process to a single page, reducing the time from minutes to seconds.",
      "Identified slow APIs and optimised SQL queries by implementing indexing and refining WHERE clauses, reducing their response time from 20-30 secs to just 1-2 seconds.",
      "Developed an internal admin dashboard to monitor the product using Next.js and Express.js.",
      "Designed and deployed scalable HTTP APIs using Node.js and .NET Core to support high-traffic features.",
      "Collaborated with external partners to integrate their products into our website.",
      "Developed a highly accurate (97%) user journey tracking system.",
      "Worked as an intern for 6 months before transitioning to a full-time role.",
      "Recognized twice as the Best Performer for consistently delivering high-impact solutions and proactively upskilling to enhance team efficiency.",
    ],
    Stack: [
      "React",
      "Next.js",
      "Node.js",
      "Express.js",
      "SQL Server",
      "MongoDB",
      "MUI",
      ".NET Core",
    ],
    active: 1,
    isCurrent: true,
  },
  {
    name: "LetsEndorse",
    location: "Bengaluru",
    position: "Frontend Web Developer Intern",
    duration: "June 2021 - August 2021",
    description: [
      "Redesigned and coded the existing website, following best practices, resulting in an enhanced user experience, improved navigation and engagement.",
      "Improved their existing dashboard to monitor data on various businesses.",
      "Plotted them on a map using Leaflet and Tom Tom’s API, making it an interactive map.",
      "Added custom filters for enhanced data exploration, and forms to add, delete, and view data.",
      "Designed and implemented the User Management and Order Management Page of the Admin Panel.",
      "Created a platform to visualize, store, and clean the data about various marketplaces.",
      "Added various forms using Formik.",
    ],
    Stack: ["React", "MUI", "HTML5", "CSS", "API", "Leaflet", "TomTom API"],
    active: 1,
    isCurrent: false,
  },
  {
    name: "Design Innovation Center",
    location: "Chandigarh",
    position: "Web Development Intern",
    duration: "July 2022 - August 2022",
    description: [
      "Worked as a full stack web developer, it was more of a training based internship",
      "Created a Publishing Company's Full stack website which had features like place an order, a book store to buy products from, an admin panel to manage that book store, contact form, their gallery etc.",
      "Created an University Landing Page created using NextJs, TypeScript and Tailwind",
    ],
    active: 0,
    isCurrent: false,
    Stack: [
      "React",
      "NodeJs",
      "MySQL",
      "API",
      "Tailwind",
      "NextJs",
      "Tailwind",
    ],
  },

  // {
  //   name: "Viplus",
  //   location: "Manesar",
  //   position: "Freelance Web Developer",
  //   duration: "Oct 2021 - Dec 2021",
  //   description: [
  //     "Designed and Developed an eCommerce website as well as its admin panel by using React and Nodejs.",
  //     "Created database using MongoDB.",
  //     "Implemented maps from scratch that shows the establishments in a city using appropriate colors and labels",
  //     "I was responsible for creating all the models, routes, views and controllers needed for functionality.",
  //   ],
  //   active: 0,
  //   isCurrent: false,
  // },
];
