export const experienceList = [
  {
    name: "PolicyBazaar.com",
    location: "Gurgaon",
    position: "Software Engineer",
    duration: "Jan 2023 - Present",
    description: [
      "Been working as a full-stack developer (React, .Net, SQL Server) at Policybazaar for more than a year. I started as an intern and converted to full-time. I have also been awarded as the Rising star of our team.",
      "Developed a highly accurate (97%) user journey tracking system using React and .Net. It required having in-depth knowledge and understanding of the codebase and the product.",
      "Developed an admin dashboard to monitor the product using Next.js for UI and .Net core for creating robust APIs.",
      "Streamlined user journeys, by converting 5-10 pages journey to a single page for renewal customers. It ensured hassle-free policy renewals within seconds.",
      "Wrote complex queries in SQL server and improved existing APIs for the IVR team. Brought down the response time for the API to fetch data, from 20-30 seconds to an average of 1-2 secs.",
      "Been constantly improving the website performance by resolving bugs and optimizing components. I have always focused on enhancing user experience. Hence, I introduced error handling (Error Boundary) to our website.",
      "Collaborated with external partners to integrate their products into our website.",
    ],
    Stack: [
      "React",
      "Nextjs",
      ".Net Framework",
      "SQL Server",
      "MongoDB",
      "Tailwind",
      ".Net Core",
    ],
    active: 1,
    isCurrent: true,
  },

  {
    name: "LetsEndorse",
    location: "Bengaluru",
    position: "Web Development Intern",
    duration: "June 2021 - August 2021",
    description: [
      "Redesigned their existing website, and coded it in React following best practices. It enhanced the user experience and functionality which improved the navigation and engagement.",
      "Improved their existing dashboard to monitor data on various businesses.",
      "Plotted them on a map using Leaflet and Tom Tom’s API, it was an interactive map.",
      "Added custom filters for enhanced data exploration and forms to add, delete and view data.",
      "Designed and implemented the User Management and Order Management Page of the Admin Panel.",
      "Created a platform to visualize, store, and clean the data about various marketplaces.",
    ],
    Stack: ["React", "Html5", "CSS", "API", "Maps API", "Leaflet"],
    active: 1,
    isCurrent: false,
  },

  {
    name: "Design Innovation Center",
    location: "Chandigarh",
    position: "Web Development Intern",
    duration: "July 2022 - August 2022",
    description: [
      "Worked as a full stack web developer, it was more of a training based internship",
      "Created a Publishing Company's Full stack website which had features like place an order, a book store to buy products from, an admin panel to manage that book store, contact form, their gallery etc.",
      "Created an University Landing Page created using NextJs, TypeScript and Tailwind",
    ],
    active: 0,
    isCurrent: false,
    Stack: [
      "React",
      "NodeJs",
      "MySQL",
      "API",
      "Tailwind",
      "NextJs",
      "Tailwind",
    ],
  },

  // {
  //   name: "Viplus",
  //   location: "Manesar",
  //   position: "Freelance Web Developer",
  //   duration: "Oct 2021 - Dec 2021",
  //   description: [
  //     "Designed and Developed an eCommerce website as well as its admin panel by using React and Nodejs.",
  //     "Created database using MongoDB.",
  //     "Implemented maps from scratch that shows the establishments in a city using appropriate colors and labels",
  //     "I was responsible for creating all the models, routes, views and controllers needed for functionality.",
  //   ],
  //   active: 0,
  //   isCurrent: false,
  // },
];
